### ISSUE TITLE
The list contains non-domain entries

### ISSUE THREAD

**Issue by e1himself** [Kikobeats/free-email-domains#12]
Hi!

Thanks for your work on this package! :+1: 

So I've installed the packaged and checked the `domains.json` file inside the `node_modules/free-email-domains` folder to find out it contains lots of non-domain entries. I guess this is an unintentional glitch of parsing the source Hubspot page (https://knowledge.hubspot.com/forms/what-domains-are-blocked-when-using-the-forms-email-domains-to-block-feature)? 

```json
[
  "You",
  "can",
  "also",
  "<a",
  "href=\"https://f.hubspotusercontent40.net/hubfs/2832391/Marketing/Lead-Capture/free-domains-1.csv\"",
  "rel=\"noopener\">download",
  "a",
  "CSV",
  "file</a>",
  "that",
  "includes",
  "all",
  "the",
  "domains",
  "below.",
  "This",
  "file",
  "can",
  "be",
  "helpful&nbsp;if",
  "you",
  "need",
  "to",
  "make",
  "any",
  "manual",
  "modifications",
  "to",
  "the",
  "list",
  "and",
  "paste",
  "the",
  "resulting",
  "list",
  "into",
  "the",
  "<a",
  "href=\"/forms/block-form-or-pop-up-form-submissions-from-specific-email-domains\"",
  "rel=\"noopener\"",
  "target=\"_blank\"><em>Email",
  "domains",
  "to",
  "bloc</em><em>k</em>",
  "field</a>",
  "when",
  "you're",
  "creating",
  "a",
  "form.",
  "0-mail.com",
  "027168.com",
  "0815.su",
  "0sg.net",
  "10mail.org",
  "10minutemail.co.za",
  "11mail.com",
  "123.com",
  "123box.net",
  "123india.com",
```

Thanks in advance!

**Comment by Kikobeats** [comment]
ops, that is not an intentional thing, looks like the delimiter for generating the list is poorly typed:

https://github.com/Kikobeats/free-email-domains/blob/master/scripts/postinstall.js#L14

Can you take a look and make a PR? 😄
