### ISSUE TITLE
Error while installing free-email-domains package

### ISSUE THREAD

**Issue by RaghuVarmaPinnelli** [Kikobeats/free-email-domains#3]
Hi,
While I'm trying to install 'free-email-domains' package I'm getting below error
Command Executed: 
npm install -g free-email-domains

Error :
> free-email-domains@1.0.1 postinstall C:\Users\User\AppData\Roaming\npm\node_modules\free-email-domains
> curl -sL https://knowledge.hubspot.com/articles/kcs_article/forms/what-domains-are-blocked-when-using-the-forms-email-domains-to-block-feature | ./scripts/po
stinstall

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! free-email-domains@1.0.1 postinstall: `curl -sL https://knowledge.hubspot.com/articles/kcs_article/forms/what-domains-are-blocked-when-using-the-forms
-email-domains-to-block-feature | ./scripts/postinstall`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the free-email-domains@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-05-17T11_21_52_382Z-debug.log

**Comment by Kikobeats** [comment]
The package run a postinstall script that uses bash to be executed, not sure how to do that at windows.

PRs are welcome 🙂
