### ISSUE TITLE
Quick way to use with typescript import module

### ISSUE THREAD

**Issue by samuel-pipelaunch** [Kikobeats/free-email-domains#35]
Hi, just a quick tip that can be added to the documentation

1. Create a new file called `index.d.ts` inside this module root folder
2. Copy this content
```
const freeEmailDomains = require('./domains.json')
export default freeEmailDomains;
```
3. Use it on your typescript file as  
```
import freeEmailDomains from "free-email-domains";

...
const isFreeEmailDomain = freeEmailDomains.includes('gmail.com');
```

**Comment by brandart** [comment]
why did you close this?

have you got a solution for this?

**Comment by karlhorky** [comment]
@samuel-pipelaunch would you be open to creating a PR for this?

@Kikobeats would you accept a PR to add a simple 2-line TypeScript typings file for the package?

**Comment by Kikobeats** [comment]
Yea I'll accept a PR for this 🙂

**Comment by karlhorky** [comment]
Open at #36
