### ISSUE TITLE
got package update - to a non-vulnerable version

### ISSUE THREAD

**Issue by Dzixxx** [Kikobeats/free-email-domains#38]
Hi,
Dependabot found that `got` in v11 contains cacheable-request which is vulnerable to Regular Expression Denial of Service 
Is there a plan to update got to v12? pweaseee 🥺 

Kind regards
Dziczek

**Comment by Kikobeats** [comment]
fixed – can you test the latest version?

**Comment by Dzixxx** [comment]
Wow that was fast 😂 and still works ❤️
Thank U!
