### ISSUE TITLE
Post install script failure

### ISSUE THREAD

**Issue by sumindersingh** [Kikobeats/free-email-domains#40]
below is the stack trace. 

1075 verbose stack Error: free-email-domains@1.0.32 postinstall: `node scripts/postinstall.mjs`
1075 verbose stack Exit status 1
1075 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
1075 verbose stack     at EventEmitter.emit (events.js:400:28)
1075 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1075 verbose stack     at ChildProcess.emit (events.js:400:28)
1075 verbose stack     at maybeClose (internal/child_process.js:1058:16)
1075 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
1076 verbose pkgid free-email-domains@1.0.32
1077 verbose cwd C:\~\~
1078 verbose Windows_NT 10.0.14393
1079 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "free-email-domains@1.0.32"
1080 verbose node v14.18.1
1081 verbose npm  v6.14.15
1082 error code ELIFECYCLE
1083 error errno 1
1084 error free-email-domains@1.0.32 postinstall: `node scripts/postinstall.mjs`
1084 error Exit status 1
1085 error Failed at the free-email-domains@1.0.32 postinstall script.

**Comment by Kikobeats** [comment]
No problem; The library includes a fallback file with the up-to-date data for case like this

So even the postinstall failed, you can still use the library 🙂
