### ISSUE TITLE
Includes disposable domains as well

### ISSUE THREAD

**Issue by AndreiIgna** [Kikobeats/free-email-domains#5]
This is a good list, but from the name of repo it implies it's a list of domains that provide free email.
The wording on HubSpot is "blocked domains", which is not easily seen here.

Only want to start a discussion and the Issues seemed the best option atm.
Based on the name of this list "free-email-domains", it wasn't clear from beginning what's actually on the list before checking a few domains. Example:
- gmail.com - free email provider
- me.com - free email provider
- mailinator.com - disposable email domain
- mt2015.com - disposable email domain

Is there a way to differentiate the type of domains? Want to integrate something like this in a project and looking to have these 2 distinct lists. This repo https://github.com/ivolo/disposable-email-domains is a great resource for disposable email domains, but there doesn't seem to be a similar one for free email domains yet.

Cheers

**Comment by Kikobeats** [comment]
happy if we can separate into two lists – although the current list is generated based on a script over HubSpot web.
